export const AUDIT = {
    READAUDIT : "audit.read",
    READ_AUDIT_CALENDAR : "audit.readcalendar",
    SCHEDULE : "audit.schedule",
    RESCHEDULE : "audit.reschedule",
    PLANNING : "audit.planning",
    APPROVE_PLANNING : "audit.approve.planning",
    REJECT_PLANNING : "audit.reject.planning",
    EMMIT_REPORT : "audit.emmit.report",
    APPROVE_REPORT : "audit.approve.report",
    REJECT_REPORT : "audit.reject.report",
    EDIT_REJECT_REPORT : "audit.edit.rejectedreport",
    DELETE : "audit.delete",
    EXPORT : "audit.export",
    ADD_FINDINGS : "audit.addfindings",
};