import { CorrectiveActionState } from "./CorrectiveActionState";
import { CorrectiveActionEvidence } from "./CorrectiveActionEvidence";
import { CorrectiveActionFishbone } from '../corrective-action/corrective-action-fishbone.model';

export class CorrectiveAction{
    workflowId: String;
    correctiveActionID: number;
    correctiveActionState: CorrectiveActionState;
    correctiveActionStateID: Number;
    creationDate;
    dateTimeEfficiencyEvaluation;
    description: String;
    effectiveDateImplementation;
    emitterUser;
    emitterUserID;
    RelatedFindingId: Number;
    finding;
    findingID: Number;
    impact;
    isEffective: boolean;
    maxDateEfficiencyEvaluation;
    maxDateImplementation;
    rootReason: string;
    // EmissionPlantId: Number;
    // EmissionSectorId: Number;
    plantLocationID: Number;
    sectorLocationID: Number;
    responisbleUser;
    sectorPlantLocation;
    sectorPlantTreatment;
    plantTreatmentID: Number;
    sectorTreatmentID: Number;
    responsibleUserID: String;
    lastResponsibleUserID: String;
    reviewerUser;
    reviewerUserID: Number;
    workGroup;
    Evidences: CorrectiveActionEvidence[];
    evidences;
    FileNamesToDelete: String[];
    correctiveActionFishbone: CorrectiveActionFishbone[];
    evaluationCommentary: String;
    userCorrectiveActions;
    deadlineDateEvaluation;
    deadlineDatePlanification;
    sectorPlantLocationName;
    sectorPlantTreatmentName;
    responsibleUserFullName;
    correctiveActionStateName;
    correctiveActionStateCode;
    reviewerUserFullName;
    correctiveActionStateColor;
    tasks;
    isResponsibleUser;
    editAsResponsibleRefferrent;
    editAsReviewerRefferrent;
    isReviewerUser;
    editAsRefferrent;
}

